spring:
  application:
    name: service-eureka-user #服务名称
server:
  port: 8080 #端口
eureka:
  client:
    service-url:
      defaultZone: http://cloud-demo-eureka-server:8080/eureka/  #服务中心地址
